name: SkyHighCinema
favicon: null
layout_spectrum: 0
typography_spectrum: 0.47523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262626'
    - '#fffffe'
    - '#7c8a95'
    - '#c7bcbc'
    - '#5c611d'
  brandStrength: 0.8125
  lightness: 0.45268844650126994
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
