name: SkyHighCinema
favicon: null
layout_spectrum: 0.548961388412863
typography_spectrum: 0.7111348761245608
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6555383936502039
  lightness: 0.45268844650126994
  saturation: 0.04573396407067776
  rhythmicContrast: 0.6471089522819966
purpose: []
